"""vimos_products_changes

Revision ID: 1eaec2e10b3b
Revises: 350c0551194f
Create Date: 2023-09-13 12:28:03.713325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eaec2e10b3b'
down_revision = '350c0551194f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vimos_products', sa.Column('gcode', sa.String(length=512), nullable=True))
    op.add_column('vimos_products', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('vimos_products', sa.Column('measurement', sa.String(length=64), nullable=True))
    op.add_column('vimos_products', sa.Column('category', sa.String(length=512), nullable=True))
    op.drop_column('vimos_products', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vimos_products', sa.Column('url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('vimos_products', 'category')
    op.drop_column('vimos_products', 'measurement')
    op.drop_column('vimos_products', 'created_at')
    op.drop_column('vimos_products', 'gcode')
    # ### end Alembic commands ###
