"""analytics

Revision ID: 350c0551194f
Revises: 3b7d0c691567
Create Date: 2023-09-06 11:08:58.613468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350c0551194f'
down_revision = '3b7d0c691567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petrovich_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vimos_name', sa.String(length=512), nullable=True),
    sa.Column('vimos_price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('petrovich_name', sa.String(length=512), nullable=True),
    sa.Column('petrovich_price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('vimos_category', sa.String(length=128), nullable=True),
    sa.Column('abs_diff', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('relative_diff', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vimos_name', 'created_at', name='petrovich_analytics_unique')
    )
    op.create_index(op.f('ix_petrovich_analytics_id'), 'petrovich_analytics', ['id'], unique=False)
    op.create_table('saturn_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vimos_name', sa.String(length=512), nullable=True),
    sa.Column('vimos_price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('saturn_name', sa.String(length=512), nullable=True),
    sa.Column('saturn_price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('vimos_category', sa.String(length=128), nullable=True),
    sa.Column('abs_diff', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('relative_diff', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vimos_name', 'created_at', name='saturn_analytics_unique')
    )
    op.create_index(op.f('ix_saturn_analytics_id'), 'saturn_analytics', ['id'], unique=False)
    op.create_table('stroyudacha_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vimos_name', sa.String(length=512), nullable=True),
    sa.Column('vimos_price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('stroyudacha_name', sa.String(length=512), nullable=True),
    sa.Column('stroyudacha_price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('vimos_category', sa.String(length=128), nullable=True),
    sa.Column('abs_diff', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('relative_diff', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vimos_name', 'created_at', name='stroyudacha_analytics_unique')
    )
    op.create_index(op.f('ix_stroyudacha_analytics_id'), 'stroyudacha_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stroyudacha_analytics_id'), table_name='stroyudacha_analytics')
    op.drop_table('stroyudacha_analytics')
    op.drop_index(op.f('ix_saturn_analytics_id'), table_name='saturn_analytics')
    op.drop_table('saturn_analytics')
    op.drop_index(op.f('ix_petrovich_analytics_id'), table_name='petrovich_analytics')
    op.drop_table('petrovich_analytics')
    # ### end Alembic commands ###
