"""leroy_products

Revision ID: 3b7d0c691567
Revises: 659ad55545ab
Create Date: 2023-08-31 17:25:02.533147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7d0c691567'
down_revision = '659ad55545ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leroy_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('cart_price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('measurement', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('exists', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leroy_products_id'), 'leroy_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leroy_products_id'), table_name='leroy_products')
    op.drop_table('leroy_products')
    # ### end Alembic commands ###
